name: Terraform Workflow with Snyk Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      id: terraform_plan
      run: terraform plan 

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check for security issues 
      id: snyk_test
      run: snyk test --severity-threshold=low
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && steps.snyk_test.conclusion == 'success'
      run: terraform apply -auto-approve
